### ISSUE TITLE
Allow editing of opening date

### ISSUE THREAD

**Issue by greypiglet** [emollett/coffee-tracker#13]
- and add another field for purchase date?

**Comment by emollett** [comment]
https://github.com/emollett/coffee-tracker/commit/d365be325cc3c898003d51c1a4011baad12ab404

**Comment by emollett** [comment]
Re-opened, had only done request from body of issue (adding new field) need to allow editing too.

**Comment by emollett** [comment]
https://github.com/emollett/coffee-tracker/commit/f19741e5b567ad61ccdb14f42864558b64f112f9
