### ISSUE TITLE
Not all dependencies are included in the package.json

### ISSUE THREAD

**Issue by Joe-Davidson1802** [emollett/coffee-tracker#19]
**Describe the bug**
Not all dependencies are included in the package.json

**To Reproduce**
1. Get a clean version of site
2. Run `npm i`
3. Run `npm start`

**Expected behavior**
The site to start up successfully 

**Actual behavior**
An error is thrown because things like "mongoose", "express" and "morgan" are not installed.

**Comment by emollett** [comment]
You need to do npm i in both the coffee-tracker-front-end and
coffee-tracker-backend folders as they have their own package.json
This is a hangover from the original structure that I will fix or at least
provide better instructions for.
